# This workflow generates documentation (PDFs, interactive BOMs, board images) and fabrication
# files for JLCPCB and PCBWay. The version number and date of the design is automatically
# updated in the schematic file and on the PCB based on the GitHub release version and date.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot - Release Full Output"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

jobs:
  FabricationAndDocumentation:
    env:
      # Set this to the base filename of your project.
      BaseFileName: Campinglaterne
      # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
      Timezone: America/New_York
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the version of the GitHub release for use later.
      - name: Get GitHub release version
        id: get_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: Generate documentation and fabrication files
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/full_outputs.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.BaseFileName }}.kicad_sch
          board: ${{ env.BaseFileName }}.kicad_pcb

      # Install the zip command line tool to package up the output
      - name: Install zip
        uses: montudor/action-zip@v1

      # Zip all the documentation. Any files in the PCBWay, PDFs, Renders, and Schematic subfolder
      # are automatically included.
      - name: Zip documentation
        run: zip -qq -r "../${{ env.BaseFileName }}-fab_outputs.zip" PCBWay PDFs Renders Schematic
        working-directory: ${{ env.OutputFolder }}

      # Upload all the zip files to the release. 
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.BaseFileName }}-fab_outputs.zip
